Vagrant.configure("2") do |config|
  config.vm.define "workplace" do |node|
    config.vm.box = "generic/ubuntu2204"
    node.vm.hostname = "workplace"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "workplace"
      vb.memory = 1024
      vb.cpus = 1
      vb.gui = false
      vb.linked_clone = true
    end
    node.vm.provision "shell", path: "./config/workplace/workplace_provision.sh"
    node.vm.synced_folder "../", "/vagrant"
  end
  config.vm.define "vpn1" do |node|
    node.vm.box = "debian/bookworm64"
    node.vm.hostname = "vpn1"
    node.vm.network "private_network", ip: "192.168.56.10"
    node.vm.network "private_network", ip: "172.30.74.74", virtualbox__intnet: "trusted", auto_config: false
    node.vm.provider "virtualbox" do |vb|
      vb.name = "vpn1"
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = false
      vb.linked_clone = true
    end
    node.vm.provision "shell", path: "./config/openvpn/openvpn_provision.sh"
    node.vm.provision "shell", inline: "shutdown -r"
    node.vm.synced_folder "../", "/vagrant"
  end
  config.vm.define "server" do |node|
    node.vm.box = "debian/bookworm64"
    node.vm.hostname = "server"
    node.vm.network "private_network", ip: "172.30.74.75", virtualbox__intnet: "trusted"
    node.vm.network "forwarded_port", guest: 1389, host: 10389 # ldap
    node.vm.provider "virtualbox" do |vb|
      vb.name = "server"
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = false
      vb.linked_clone = true
    end
    node.vm.provision "shell", path: "./config/server/server_provision.sh"
    node.vm.synced_folder "../", "/vagrant"
  end
end
