- name: copy node_exporter service files
  copy: 
    src: etc/systemd/system/node_exporter.service 
    dest: /etc/systemd/system/

- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/node_exporter.linux-amd64.tar.gz
    checksum: sha256:https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/sha256sums.txt

- name: untar node_exporter
  unarchive:
    src: /tmp/node_exporter.linux-amd64.tar.gz
    remote_src: true
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    extra_opts:
    - --strip-components
    - "1"
    exclude:
    - LICENSE
    - NOTICE

- name: Start node_exporter service
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes
